name: Loot Tables

on:
  workflow_call:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - run: dotnet restore src/LootTables/LootTables.csproj
      - run: dotnet build src/LootTables/LootTables.csproj --configuration Release
      - run: dotnet test tests/LootTables.Tests/LootTables.Tests.csproj --configuration Release
