name: 🚀 Game Mechanics Master Pipeline

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  common:
    if: endsWith(needs.detect-commit.outputs.msg, '--common') || endsWith(needs.detect-commit.outputs.msg, '--build')
    uses: ./.github/workflows/common.yml
