name: 🚀 Game Mechanics Master Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  common:
    if: endsWith(needs.detect-commit.outputs.msg, '--build')
    uses: ./.github/workflows/common.yml
