name: 🚀 Game Mechanics Master Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  common:
    uses: ./.github/workflows/common.yml
  loot-tables:
    uses: ./.github/workflows/loot-tables.yml
